// <auto-generated />
namespace NivelAccesDate_ORM_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DataBaseCodeFirstV_13 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DataBaseCodeFirstV_13));
        
        string IMigrationMetadata.Id
        {
            get { return "202210241653172_DataBaseCodeFirstV_13"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
