// <auto-generated />
namespace NivelAccesDate_ORM_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Adaugare_campuri_effect_integer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adaugare_campuri_effect_integer));
        
        string IMigrationMetadata.Id
        {
            get { return "202301051112061_Adaugare_campuri_effect_integer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
