// <auto-generated />
namespace NivelAccesDate_ORM_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class test_migrare_imagine_bun : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test_migrare_imagine_bun));
        
        string IMigrationMetadata.Id
        {
            get { return "202301091701373_test_migrare_imagine_bun"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
