// <auto-generated />
namespace NivelAccesDate_ORM_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class tests_update_foreign_key : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tests_update_foreign_key));
        
        string IMigrationMetadata.Id
        {
            get { return "202301071922491_tests_update_foreign_key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
