// <auto-generated />
namespace NivelAccesDate_ORM_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Adaugare_campuri_effect : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adaugare_campuri_effect));
        
        string IMigrationMetadata.Id
        {
            get { return "202301050938132_Adaugare_campuri_effect"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
